#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../headers/ppm.h"
#include "../headers/memory.h"

void initHeader(PPMHeader* header)
{
	header->magicNumber = PPM_MAGIC_NUMBER;


	header->width = 0;
	header->height = 0;

	header->colorLevel = 255;
}

void initPPM(PPM* ppm)
{
	PPMHeader* header = labelMalloc(sizeof(PPMHeader), "PPM Header Creation");
	initHeader(header);

	ppm->filename = NULL;
	ppm->size = 0;
	ppm->header = header;
	ppm->content = NULL;
}

PPM* createPPM(Matrix* matrix, int width, int height)
{
	PPM* ppm = labelMalloc(sizeof(PPM), "PPM Creation");// labelMalloc a PPM in the memory
	initPPM(ppm);// Init the PPM to its default value
	
	setWidth(ppm, width);// Change the width with the given one
	setHeight(ppm, height);// Change the height with the given one
	setContent(ppm, matrix);// Set the Matrix as the content of the PPM
	
	return ppm;
}

PPM* readPPM(char *input)
{
	PPM* ppm = labelMalloc(sizeof(PPM), "PPM Creation");//Create empty PPM
	initPPM(ppm);//Init PPM
	ppm->filename = labelMalloc(sizeof(input), "File Name");
	strcpy(ppm->filename, input);//Set the origin file name of the PPM

	FILE* in = fopen(input, "rb");//Open the orignal file

    fseek(in, 0L, SEEK_END);
    int size = ftell(in);//Calculate the file size
    ppm->size = size;//Set the file size of the PPM

    fseek(in, 0L, SEEK_SET);//Go Back to start
    
    int requireDone = 0;
    
    while(requireDone < 3)
    {
    	char c;
		int length = 0;
		char buffer[12];// The theorical max length of this line is 5 (the width) + 5 (the height) + 1 (the space between) + 1 (The end of line char)

		do
		{
			if(length < 12)
			{
				fread(&buffer[length], sizeof(char), 1, in);
				c = buffer[length];
			}
			else
			{
				fread(&c, sizeof(char), 1, in);
			}
			
			length++;
		}while(c != '\n');//Read the dimension line
		
		if(buffer[0] != '#')
		{
			if(requireDone == 0)
			{
				ppm->header->magicNumber = labelMalloc(sizeof(char) *2, "Magic Number");//Init the magic number
				ppm->header->magicNumber[0] = buffer[0];//Set the magic number
				ppm->header->magicNumber[1] = buffer[1];
			}
			else if(requireDone == 1)
			{

				buffer[length - 1] = ' ';//Replace the end of line for no interpreting by atoi
				ppm->header->width = atoi(strtok(buffer, " "));//Set the width Width
				ppm->header->height = atoi(strtok(NULL, " "));//Set the Height
			}
			else if(requireDone == 2)
			{
				char color[3];//The color buffer
				color[0] = buffer[0];
				color[1] = buffer[1];
				color[2] = buffer[2];
				
				ppm->header->colorLevel = atoi(color);//Set the color level with cast to int
			}
			requireDone++;
		}
	}
	
	ppm->content = createMatrix(ppm->header->width, ppm->header->height);//Init the first dimension of the matrix
	for(int y = 0; y < ppm->header->height; y++)
	{
		for(int x = 0; x < ppm->header->width; x++)
		{
			unsigned char bgrpix[3];//The RGB Buffer
       		fread(&bgrpix,sizeof(unsigned char),3,in);//Read the RGB values

       		Pixel* pixel = getRGB(bgrpix[0], bgrpix[1], bgrpix[2]);//Create the pixel from RGB
			setPixel(ppm,x, y, pixel);//Set the pixel

		}
	}
	
	setColumns(getContent(ppm), getWidth(ppm));
	setLines(getContent(ppm), getHeight(ppm));

    fclose(in);
    return ppm;
}

int writePPM(char* output, PPM* ppm)
{
	int writed = 0;//The number of byte writed
	FILE* out = fopen(output, "wb");//Open the output file

	fprintf(out, "%c%c\n", ppm->header->magicNumber[0], ppm->header->magicNumber[1]);//Write the magic number
	writed += sizeof(char) * sizeof(ppm->header->magicNumber) + sizeof(char);//Add the magic number size to the writed file size
	
	fprintf(out, "#PPM Generated by the Pixscalling Program\n");//Write the automatic Commentary
	writed += sizeof(char) * 42;
	
	fprintf(out, "%i %i\n", ppm->header->width, ppm->header->height);//Write the dimensions
	writed += sizeof(int) * 2 + sizeof(char) * 2;//add the dimension

	fprintf(out, "%i\n", ppm->header->colorLevel);
	writed += sizeof(int) + sizeof(char);

	for(int y = 0; y < ppm->header->height; y++)
	{
		for(int x = 0; x < ppm->header->width; x++)
		{
			fprintf(out, "%c%c%c", getRed(getPixel(ppm, x, y)), getGreen(getPixel(ppm, x, y)), getBlue(getPixel(ppm, x, y)));
			writed += sizeof(Pixel);
		}
	}

	fclose(out);
    return writed;
}

Pixel* getPixel(PPM* ppm, int x, int y)
{
	return select(ppm->content, x, y); //Select the pixel from the content Matrix
}

int getWidth(PPM* ppm)
{
	return ppm->header->width; // Return the width in the PPM header
}

int getHeight(PPM* ppm)
{
	return ppm->header->height; //Return the height in the PPM header
}

int getPixelQuantity(PPM* ppm)
{
	return matrixSize(ppm->content); // Return the amount of pixel in the matrix
}

void setWidth(PPM* ppm, int width)
{
	ppm->header->width = width; // Change the width in the PPM header
}

void setHeight(PPM* ppm, int height)
{
	ppm->header->height = height; // Change the height in the PPM header
}

Matrix* getContent(PPM* ppm)
{
	return ppm->content; // Return the content Matrix 
}

void setContent(PPM* ppm, Matrix* content)
{
	removeMatrix(getContent(ppm));
	ppm->content = content;// Change the pointer to the new matrix
}

void setPixel(PPM* ppm, int x, int y, Pixel* pixel)
{
	set(getContent(ppm), x, y, pixel);//Set pixel of the Matrix to a new pixel
}

void removePPMHeader(PPMHeader* header)
{
	if(header != NULL)
	{
		if(header->magicNumber != NULL && header->magicNumber != PPM_MAGIC_NUMBER)
		{
			freeLabel(header->magicNumber); // Remove the magic number pointer
		}
		
		freeLabel(header); // Remove the entiere header
	}
}

void removePPM(PPM* ppm)
{
	if(ppm != NULL)
	{
		removePPMHeader(ppm->header);// Remove the header
		removeMatrix(ppm->content);// Remove the content Matrix
		
		if(ppm->filename != NULL)
		{
			freeLabel(ppm->filename); // Remove the filename pointer
		}
		
		freeLabel(ppm);// Remove the PPM
	}
}
